### ISSUE TITLE
Breaking changes in Leaflet 0.8-dev

### ISSUE THREAD

**Issue by louh** [pelias/leaflet-plugin#1]
Just playing with adding this in a Tangram demo, which uses Leaflet 0.8-dev. The `L.Util. limitExecByInterval` method has been renamed to `L.Util.throttle`. (See [CHANGELOG](https://github.com/Leaflet/Leaflet/blob/98bf92530f56c0bee1f0764e0934a25db6a6692d/CHANGELOG.md#other-breaking-api-changes))

Here is my test repo where I just made the change locally:
https://github.com/louh/carousel/blob/pelias-geocoder/lib/leaflet-geocoder/pelias-leaflet-geocoder.js#L267

**Comment by bcamper** [comment]
I've made Tangram compatible with leaflet 0.7.x and 1.x (0.8 is becoming 1.0), generally by testing for different method names. I think you can use the same approach here to make it work for both.

**Comment by bcamper** [comment]
(Note only leaflet 1.x supports continuous zoom, which is one reason we use it in our demos.)

**Comment by hkrishna** [comment]
Thank you for reporting this issue. The following commit resolves it 

https://github.com/pelias/leaflet-geocoder/commit/abb1fddd75e5c7dbb422033a4fe7a79fb4ab56fe
