### ISSUE TITLE
Reintroduce zoom buttons for desktop?

### ISSUE THREAD

**Issue by riordan** [pelias/leaflet-plugin#10]
I know we had decided to simplify the mobile UX (#7) during out last discussion by removing the zoom buttons while keeping the search bar visible at all times (by default, with the option to re-enable still in the codebase).

That said, I don't remember if we were going to also remove the zoom buttons for the desktop.

<img width="348" alt="pelias_demo" src="https://cloud.githubusercontent.com/assets/227472/8621722/311b3756-26f5-11e5-8697-471607e3f7df.png">

Right now, the user can zoom into a target by clicking, allowing them to increase zoom levels, but they are left without the ability to zoom out.

What do we think about reintroducing the zoom buttons when it's on desktop mode?

**Comment by orangejulius** [comment]
I have always zoomed in and out with the scroll wheel, Is that not how everyone else does it? (I'm genuinely curious because this isn't the first time that it's seemed like lack of zoom buttons has been missed on a map product)

**Comment by louh** [comment]
Currently the demo _is_ showing zoom buttons on desktop, so is this issue still relevant?

But here's my answer anyway: yes, we should put zoom buttons on desktop. There are lots of "simple" gestures that are non-obvious to people who are legitimately not computer savvy. If you encounter a map for the first time and did not know how to zoom in, does a scroll wheel imply scroll the map? Or zoom? Which would you guess? What happens if a map is embedded into a page, and scroll-to-zoom is disabled (see Stamen's [Checklist for Maps](http://content.stamen.com/stamens-checklist-for-maps) for why this is starting to be common practice).

**Comment by orangejulius** [comment]
@lou, that totally makes sense. Definitely seems like we should keep them around then.

**Comment by louh** [comment]
Hey, I'd like to drop a little bit of implementation detail here.

So I've mentioned this in other places before, but detecting the difference between a mobile and desktop device is really tricky. So, while it's useful to talk about features and user experience divided into these two separate buckets, we don't really have a sure-fire way to differentiate between the two on the implementation side. And The Best Way to do it is highly dependent on a lot of contextual factors.

The context that will drive implementation of the _plugin_ (and this is not saying anything about the implementation of a similar input in other situations, like the web map or even standalone Mapzen-branded demos) is how much I can rely on Leaflet's own internal logic and abilities to differentiate between mobile and desktop experience. And what they do is not really differentiate between devices but whether it detects touch capability. (More precisely: whether the browser is capable of receiving a touch event.)

When Leaflet detects a touch-enabled browser, it appends the `leaflet-touch` class to the map container. So anytime you look at a Leaflet map on a phone and there's bigger buttons than usual, it's driven by the presence of that class.

This gives us a really easy, really dumb way of hiding zoom buttons "on mobile" (more precisely: hiding zoom buttons when a user can use a finger to pinch zoom or pan the map) by just doing this in CSS:

``` css
.leaflet-touch .leaflet-control-zoom {
    display: none;
}
```

So, it's not quite the same as detecting a device. (And we do that sometimes, via user-agent sniffing, which comes with its own tradeoffs and I'm not sure is appropriate for the plugin.) We're just relying on Leaflet's logic which is based on detecting the browser's capability to receive a touch event. It's a tiny distinction, but one that I think will help shape some of these conversations about plugin usability and code maintenance.
