### ISSUE TITLE
Search displaying old results

### ISSUE THREAD

**Issue by hyperknot** [pelias/leaflet-plugin#104]
There is a bug with search. After a successful search, when selecting all text and replacing it with the new one, many times it just doesn't register the new text. It still goes back to the old one. 

Fixes which I found out:
- Clicking the X
- Pressing backspace once in the empty search box, before entering the new text.

Screen recording:
https://www.youtube.com/watch?v=0URWyVLcvQw&feature=youtu.be

Chrome latest, OS X 10.9.5.

**Comment by louh** [comment]
Thanks -- after a brief investigation, I've been able to duplicate the bug you're facing when the autocomplete feature is turned off. Is that the case for you?

**Comment by hyperknot** [comment]
Yes, I forgot to say, it's with autocomplete off.

**Comment by louh** [comment]
Thanks! I'm working on a fix and will update soon.

**Comment by louh** [comment]
@hyperknot, this will be fixed in the next update.

**Comment by hyperknot** [comment]
Thanks, seems to work well.
