### ISSUE TITLE
Reverse geocoding

### ISSUE THREAD

**Issue by ktjaco** [pelias/leaflet-plugin#106]
I have my own Leaflet Pelias web mage setup, and I've been trying to test out reverse geocoding set-up in the search bar. I've noticed that I can't actually search a latitude, longitude in the search bar. I noticed the same problem in your demo as well.

For example, when I try to search `40.7643, -74.0207` in your search bar the first result is from `4076,4078 Real, Capurro, Uruguay`.

**Comment by ktjaco** [comment]
Turns out it was a matter of just changing...

`control.options.geocoder = geocoder;`
to
`control.options.geocoder.reverse = geocoder;`

**Comment by riordan** [comment]
Thanks @curiousc0w. This is actually a feature we'd like to see in the core system, where searching for a lat,lon gets you a place. Thanks for flagging this @curiousc0w!

**Comment by ktjaco** [comment]
@riordan 

No problem.

Here's my `index.js` file that I have been using for my page. Line 71 is where I made my change.

https://gist.github.com/curiousc0w/d7b8eae2e2f0723c99e3#file-index-js-L71

**Comment by ktjaco** [comment]
Although... the Javascript file I've been using is from the Leaflet Control Page.

http://www.liedman.net/leaflet-control-geocoder/download/
