### ISSUE TITLE
Geocoder does not respect bounds when searching

### ISSUE THREAD

**Issue by JamesLMilner** [pelias/leaflet-plugin#108]
I am using the following code:

``` javascript
var boundingBox = L.latLngBounds( 
    L.latLng({lat: 49.62, lng:-10.7}) ,
    L.latLng({lat: 62.52, lng :4.11}) 
);

    L.control.locate().addTo(map);
    L.control.geocoder(MAPZEN_API_KEY, {
      position: 'topright',
      expanded: true,
      bounds: boundingBox
    }).addTo(map);
```

However the code brings back all sorts of results that are not in the bounding box: 

![screen shot 2016-02-04 at 15 34 34](https://cloud.githubusercontent.com/assets/8822075/12820041/471de7b0-cb55-11e5-8017-41fb8454abd2.png)

Any idea what might be going on here? Tried a variety of different bounding boxes but results always seem global. Thanks

**Comment by louh** [comment]
Hi @JamesMilnerUK, are these results from the autocomplete, or from search? Autocomplete happens each keystroke, while search only happens when you press enter.

**Comment by riordan** [comment]
Additionally, autocomplete doesn't currently operate within the constraints of a bounding box, but Search will. Autocomplete's designed to be heavily cache-able, so we try to get the best results that'll match for the most people. Sadly that means bounding boxes (with their large numbers of variable floating points) are hard to cache.

That said, one of the features we're considering is something that'll [restrict autocomplete to any region](https://github.com/pelias/api/issues/373) using Who's on First boundary ID's. Is that something that might help support your issue?

**Comment by riordan** [comment]
But yes, Search will completely respect a bounding box.

**Comment by JamesLMilner** [comment]
@louh Apologies, I didn't realise that that the Autocomplete and Search were two different functions. @riordan that would be useful, assuming that the United Kingdom counts as a country ;) Thanks for your hard work.

**Comment by riordan** [comment]
The UK's https://whosonfirst.mapzen.com/spelunker/id/85633159/ certainly
a country. And as I learned this week, we classify England as a
"Macroregion" https://whosonfirst.mapzen.com/spelunker/id/404227469/

On Thu, Feb 4, 2016 at 11:22 AM, James Milner notifications@github.com
wrote:

> @louh https://github.com/louh Apologies, I didn't realise that that the
> Autocomplete and Search were two different functions. @riordan
> https://github.com/riordan that would be useful, assuming that the
> United Kingdom counts as a country ;) Thanks for your hard work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapzen/leaflet-geocoder/issues/108#issuecomment-179927417
> .

## 

David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan https://twitter.com/riordan | gpg 235D9DC95EF6277C
https://keybase.io/riordan
Mapzen | https://mapzen.com | @mapzen https://twitter.com/search

**Comment by devinrsmith** [comment]
I've noticed this too. I think that the autocomplete api doesn't always respect the bounding box. I've attached a screenshot that shows that we are correctly passing in the same bounding box to the autocomplete endpoint, but it is returning back a different bounding box.

Is there a more appropriate place to file this issue?

![screen shot 2016-04-14 at 11 35 38 am](https://cloud.githubusercontent.com/assets/6764691/14535785/2c0102b6-0235-11e6-8b99-37d90c038f33.png)

**Comment by louh** [comment]
@devinrsmith apologies for the late response, but yes, autocomplete will not use the bounding box parameters. One would have to use the `focus` option (more: https://mapzen.com/documentation/search/autocomplete/) and it will only prioritize results around that point, it will not contain the results in a bounding box. This was a decision made by the Pelias team to keep lookup speeds fast. If you'd like to talk to them more about it, you can visit their repo here: https://github.com/pelias/pelias
