### ISSUE TITLE
Non-obvious navigation between matches for mobile

### ISSUE THREAD

**Issue by riordan** [pelias/leaflet-plugin#11]
In the current design, a user is left to figure it out for herself that she may tap the search bar again to return to her result list. We can do more to make this more obvious.

![pelias-leaflet-mobile-confuzzling](https://cloud.githubusercontent.com/assets/227472/8622042/12ebbfba-26f7-11e5-9fb0-5ca4bd24e983.gif)

But perhaps not yet... We'll revisit.

**Comment by souperneon** [comment]
@riordan @louh let's chat about this more

**Comment by louh** [comment]
Closing due to old age
