### ISSUE TITLE
autocomplete behavior

### ISSUE THREAD

**Issue by sleepylemur** [pelias/leaflet-plugin#110]
it needs to be visually clear that autocomplete results serve the sole purpose of filling out the search box. ideally autocomplete results would be in a dropdown that is directly attached to the search box, and tabbing/arrow key/clicking through the autocomplete results would affect the contents of the search box.

once enter is hit or search is clicked, then search results should be displayed.

**Comment by louh** [comment]
Added 311355cec259f2e77ec44fd93156afa0e06c10dc
