### ISSUE TITLE
How can I add custom error messages?

### ISSUE THREAD

**Issue by hno2** [pelias/leaflet-plugin#120]
I want to use it on a german website and need translated error messages.

**Comment by louh** [comment]
@hno2, that's a great question. The error messages are hard-coded into the application and that's not a desirable situation for localization. I think we can easily extract them out and figure out some interface where you can change those error messages. I'm not well versed in translation methods - is there a way you've seen that has worked for other projects (particularly Leaflet plugins) ?

**Comment by louh** [comment]
I've got a pretty good prototype for custom text strings in this branch:
https://github.com/mapzen/leaflet-geocoder/blob/text-strings/

@hanbyul-here I would love your help translating strings in this demo page so we can see it in action.
https://github.com/mapzen/leaflet-geocoder/blob/text-strings/examples/custom-strings.html

**Comment by hanbyul-here** [comment]
@louh I just pushed the kr one to the branch

**Comment by louh** [comment]
NICE! Can you also add something for `INPUT_PLACEHOLDER` and use the same thing for `INPUT_TOOLTIP`? That's where it used to say "Search" and I was testing to see if `false` would turn it off, but we should also include those in the demo.

Thanks!!!

**Comment by hanbyul-here** [comment]
@louh just added them!

**Comment by louh** [comment]
thank you!

**Comment by louh** [comment]
Closed #152, #153
