### ISSUE TITLE
Cannot get params to work

### ISSUE THREAD

**Issue by martgnz** [pelias/leaflet-plugin#131]
Using `1.6.2` I'm having trouble getting the `params` option to work. It doesn't seem to recognize any parameter that I pass (for example with `boundary.country` and `size`).

Here's my code:

``` js
var options = {
  position: 'topright',
  expanded: true,
  layers: ["locality"],
  params: {
    "boundary.country": "ESP",
    "size": 5
  }
};

var geocoder = L.control.geocoder('API_KEY', options).addTo(map);
```

Tested on latest Chrome, OSX, Leaflet 1.0.0-rc.1. The options outside of params work.

**Comment by martgnz** [comment]
Sorry to bother you @louh, but does someone else have the same bug?

I cannot find where my error is.

**Comment by louh** [comment]
Hi @martgnz,

Can you try one thing for me? Turn off autocomplete momentarily:

``` js
var options = {
  position: 'topright',
  expanded: true,
  layers: ["locality"],
  autocomplete: false,
  params: {
    "boundary.country": "ESP",
    "size": 5
  }
};
```

Now perform a search again -- you must press enter to do this without autocomplete. Do the options in params work now?

**Comment by louh** [comment]
I'm suspecting that the params you are trying do not work because they are not supported by the `/autocomplete` endpoint for Mapzen Search. Here is the [documentation for supported parameters for `/autocomplete`](https://mapzen.com/documentation/search/autocomplete/). Let me know if this is the case!

**Comment by martgnz** [comment]
Thanks for your help @louh, that was my error.

I didn't know that autocomplete was separated from the search endpoint. Now it's working fine (although autocomplete was very nice!).

**Comment by louh** [comment]
Thanks @martgnz, I'm glad you brought it up. I've clarified the instructions in README [here](https://github.com/mapzen/leaflet-geocoder/commit/3c04fe2d84d17e6a9a45daaae875cdc7d81e7a4e) to make it more clear that even though params are sent, there are different endpoints that behave differently.
