### ISSUE TITLE
Typing throttle loses the end result

### ISSUE THREAD

**Issue by binx** [pelias/leaflet-plugin#134]
If I type too fast (or too many characters) I hit a throttle that stops more requests from being made. Unfortunately when I finish typing, the final request does not get made. This leads to behavior like typing "los angeles" quickly, but only seeing autocomplete suggestions for "los a" or whatever. Currently to fix this I have to hit enter to get new autocomplete results.

**Comment by louh** [comment]
Good observation -- if a result is throttled, it doesn't try again for you automatically later.

Do you see the "too many requests" message in the dropdown at all? Or only in the console?

I think it is possible to hit the API limit for an indefinite amount of time (say, you maxed out the requests per day) so it would also not be a good idea to try again indefinitely either. It should make sense to try requests again after hitting error 429, once every `API_RATE_LIMIT`, for `x` number of tries and possibly with a cooldown timer -- e.g. once every `API_RATE_LIMIT` three times, then subsequent tries will wait slightly longer, and finally timing out after a few seconds.

**Comment by louh** [comment]
Closing due to old age
