### ISSUE TITLE
Hitting enter does not clear autocomplete suggestions

### ISSUE THREAD

**Issue by binx** [pelias/leaflet-plugin#135]
The only way I've found to clear the autocomplete dropdown is to click on a result. When I type something and hit enter (or arrow up/down in the list and hit enter) I expected the autocomplete list to go away, since I had "selected" my final search.

**Comment by louh** [comment]
Hey @binx, can you walk me through this? I tried to duplicate this but the dropdown did go away for me after pressing enter, so I might not be understanding the situation.
