### ISSUE TITLE
Autocomplete fitbounds seems to act inconsistently

### ISSUE THREAD

**Issue by binx** [pelias/leaflet-plugin#136]
I've noticed that sometimes when I arrow up/down on the autocomplete lists, the map is moved (fitBounds) to fit the bbox of the autocomplete. Other times it does not.

More confusingly, sometimes searching for a place will call fitBounds on that area, and other times it simply centers the map on that place. 

Is there a 2nd set of calls being made to provide the autocomplete list with more information, and thus typing/choosing quickly happens before the request returns?

**Comment by louh** [comment]
I _think_ what you are seeing is the difference between point and polygon results, but to clarify, are you saying that you are seeing inconsistent behavior for the _same_ result?
