### ISSUE TITLE
Use Tangram as basemap engine

### ISSUE THREAD

**Issue by riordan** [pelias/leaflet-plugin#14]
For demo site, use @Tangrams to power the basemap.

**Comment by louh** [comment]
Switched the primary demo to Tangram here: https://github.com/pelias/leaflet-geocoder/blob/master/index.html

There is also a barebones Tangram implementation here as a learning-friendly example: https://github.com/pelias/leaflet-geocoder/blob/master/examples/tangram.html

We'll have to keep other examples / demos on stock Leaflet with raster tiles for old-browser compatibility.

11/18/2015 EDIT: update links

**Comment by easherma** [comment]
FYI this issue comes up if you google using tangram for basemaps, but both of the links above no longer work. Might want to reference new links here just in case.

**Comment by louh** [comment]
@easherma, good call. I've updated the links.
