### ISSUE TITLE
No results when searching for a postcode (5 digits) in France

### ISSUE THREAD

**Issue by supakazes** [pelias/leaflet-plugin#143]
Hi,

It used to work but haven't touched anything in my code since a few weeks I imagine the service API has changed (?).

**The problem**  :
I try to search and find a city in France entering it's postcode in the geocoder, the postcode example is `75019` (Paris) and the exact query is :
`https://search.mapzen.com/v1/search?text=75019&focus.point.lat=47.27177506640826&focus.point.lon=2.724609375&layers=locality%2Caddress&boundary.country=FRA&resultsSize=10&size=10&api_key=search-GmnWoUR`

![image](https://cloud.githubusercontent.com/assets/932133/18172505/fcb818e2-7065-11e6-9bfe-261ed7d0e360.png)

I am expecting a `features` property containing an array with all localities. I'm getting one when I try and search less numbers such as `7501`
![image](https://cloud.githubusercontent.com/assets/932133/18172792/343d849a-7067-11e6-8ff6-f7d59b194cf9.png)

It seems in the first test with `75019` that this is detected as a postcode (see property `geocoding.query.parsed_text`

Is there a new restriction about postcodes ? or postcode in France ?

Thanks !

**Comment by missinglink** [comment]
hi @kazes, the query is matching on `housenumber` not on `postalcode`, the reason you are not getting matches for numbers greater than 7500 is because it's uncommon for roads to have than many houses on them.

regarding the expected behavior, I'll link a ticket to investigate why https://whosonfirst.mapzen.com/spelunker/id/421307215/#13/48.8869/2.3877 is not being found for the query `75019`.

**Comment by supakazes** [comment]
Thanks for your reply :) Yes and when there is 5 numbers the response indicates the parsed text as a postcode, so it's not looking through house numbers.

**Comment by supakazes** [comment]
Is it solved then ?

**Comment by louh** [comment]
Sorry, just cleaning house! I'm closing this because this is a Pelias / Mapzen Search issue and this is being tracked in that repository.

**Comment by supakazes** [comment]
Fair enough, thanks :)

**Comment by dianashk** [comment]
It is solved now! Cheers!
