### ISSUE TITLE
Search for "toulou" suggests first result "Toulouse" in French Guyana but expected in France

### ISSUE THREAD

**Issue by supakazes** [pelias/leaflet-plugin#145]
Hello,

Working with the geocoder I spotted what I think is an error in the datas. 
When you try to search **"toulou"** and expect to find **Toulouse in France**, the first result is acutally **"Toulouse, France" but in French Guyana** (South America). There are coordinates and it would be ok for me if the city would exist but when you search online for it, **it does not seem to exists at all**, so I think it's an error :/

Here is my query :
`https://search.mapzen.com/v1/search?text=toulou&layers=locality&boundary.country=FRA&resultsSize=10&api_key=search-GmnWoUR`

![image](https://cloud.githubusercontent.com/assets/932133/19150797/3c719192-8bc9-11e6-8efb-af546b08357d.png)

And when you search for **"toulouse"** you have the **correct place in France** :

![image](https://cloud.githubusercontent.com/assets/932133/19150873/b642c0fe-8bc9-11e6-98b3-c01f04aa782d.png)

Can you tell me if this is an error in datas or if this result is as expected ?
Thanks !

**Comment by louh** [comment]
cc @dianashk

**Comment by supakazes** [comment]
Hi, I just come back to up the issue :) 
I know you're busy sorry but do you have any idea about this ?
Thanks !

**Comment by orangejulius** [comment]
Hi @kazes,
Thanks for reporting this. I work on the [Pelias](http://github.com/pelias/) team that runs the Mapzen Search service you're querying. This is definitely a bug in our data, there's certainly no Toulouse in French Guiana. The data comes from the [Geonames](http://geonames.org/) project, which has a lot of good data but also many issues.

I've deleted this record from our database, so Mapzen Search [now returns correct results](http://pelias.github.io/compare/#/v1/search%3Flayers=locality&boundary.country=FRA&text=toulou)
![screenshot from 2016-10-26 13-28-51](https://cloud.githubusercontent.com/assets/111716/19737117/27a63cd8-9b80-11e6-9cd3-254a74b85691.png)

I've also deleted it from Geonames, although I have no idea how long that will take to propagate into their published dataset that we import. In any case, we'll also be sure to write a filter to remove this record when we do future builds, so this issue shouldn't come up any more. If it does, or if anything else strange happens, please let us know!

Thanks,
Julian

**Comment by supakazes** [comment]
Hi Julian, thanks very much.
I'm happy to contribute to find errors to fix :) No worries for the time to propagate as long as it's fixed that's perfect. 
Cheers !

**Comment by supakazes** [comment]
I've just tested it and I can confirm it works fine now. I'm closing this issue :)
