### ISSUE TITLE
Geocoding Recently Built Buildings in NYC

### ISSUE THREAD

**Issue by ashron24** [pelias/leaflet-plugin#147]
My mapzen geocoder is failing to find some new-ish buildings in NYC. For example, it can't find 169-30 Baisley Boulevard in Queens. This is a building that was constructed about a year ago. Can someone tell me how often the data gets updated?

**Comment by orangejulius** [comment]
Hey @ashron24,
Mapzen Search updates our data once a week. The data for NYC addresses comes mainly from [OpenAddresses](http://openaddresses.io/), which in turn gets its NYC data through the [NYC Address Points data set](https://data.cityofnewyork.us/City-Government/NYC-Address-Points/g6pj-hd8k) (link unfortunately requires signup). Surprisingly, this dataset says it was updated just last week! However checking the latest data, 169-30 Baisley isn't in there.

Fortunately, we also get address data from [OpenStreetMap](http://www.openstreetmap.org/#map=18/40.68110/-73.77349), which is of course editable by anyone, and it looks like 169-30 Baisley isn't there either, so it would be great to add it if you're up for it.

**Comment by ashron24** [comment]
Great, thanks for letting me know! I added it to the map. Its an 8 floor
building with 54 apartments, built a couple of years ago. Thanks again,

Asher
