### ISSUE TITLE
Attach search functionality to existing input

### ISSUE THREAD

**Issue by stoil** [pelias/leaflet-plugin#149]
Congratulations for the good work, this plugin is awesome. 
I am building a React app and I am using leaflet (1.0.2) map for it. Is there any chance to attach the search functionality to an existing input element instead of creating an input in the onAdd method?

**Comment by louh** [comment]
Hi @stoil,
Is your existing input element in React? If so, this might work better for your needs: https://github.com/abec/react-autosuggest-geocoder (you would have to wire it up to Leaflet yourself, though.)
