### ISSUE TITLE
Plugin breaks with latest Leaflet

### ISSUE THREAD

**Issue by hyperknot** [pelias/leaflet-plugin#150]
With Leaflet master (will be 1.0.4) this plugin produces the following error:

```
Uncaught TypeError: Cannot read property 'Events' of undefined
    at leaflet-geocoder-mapzen.js:38
    at leaflet-geocoder-mapzen.js:23
    at leaflet-geocoder-mapzen.js:25
```

The actual error message is referring to `L.Mixin.Events`.

Minimal example:
https://playground-leaflet.rhcloud.com/qatu/1/edit?html,output

Reported in Leaflet:
https://github.com/Leaflet/Leaflet/issues/5358

**Comment by louh** [comment]
Thanks for the report, @hyperknot. I'll be investigating this today.

**Comment by louh** [comment]
As of commit https://github.com/mapzen/leaflet-geocoder/commit/a215a53b993d2fd071e75ae494906f49687b9aad

If `L.Evented` is present on Leaflet, we include `L.Evented.prototype`, or we fall back to `L.Mixin.Events`.

**Comment by louh** [comment]
Published https://github.com/mapzen/leaflet-geocoder/releases/tag/v1.8.0 which should address this!
