### ISSUE TITLE
Marker doesnt show on search :(

### ISSUE THREAD

**Issue by enocholumide** [pelias/leaflet-plugin#159]
:(

![image](https://cloud.githubusercontent.com/assets/24214602/24583407/9b21cf58-1748-11e7-8141-dc8443a7b976.png)

![image](https://cloud.githubusercontent.com/assets/24214602/24583400/7cda830a-1748-11e7-8355-917ea99d49f7.png)

**Comment by louh** [comment]
Hi @enocholumide,

I have some follow up questions to see if I can narrow down the problem.

1. are you supplying custom marker options? If so, can you paste in what they are?
2. are you using a build process that changes stylesheets or packages images for you? (e.g. webpack, etc)

Thanks!

**Comment by enocholumide** [comment]
Hi @louh 

1. When I could'nt get the marker to display, I had to turn make the marker display false, then I extracted the address, latitude and longitude information to create my own custom marker.

2. I am developing with angular2, but I have my own css style sheets, i dont imagine it will overide the styles of the mapzen plugin.

// initialize mapzen geocoder
    var geocoder = L.control.geocoder('mapzen-key', 
                        { position: 'bottomright',
                          panToPoint: true,
                          fullwidth: true,
                          expanded: false,
                          focus: true,                        // search nearby
                          placeholder: 'Search nearby',
                          markers: false,                     // disable mapzen markers we just need the details from mapzen
                        }).addTo(this._map);

      // get details from mapzen
      geocoder.on('select', function (e) {
          
          var _lat = e.latlng.lat;
          var _lng = e.latlng.lng;
          var _selectedAddress = e.feature.properties.label;

          console.log('You have selected', _selectedAddress, _lat, _lng); // :)
          
          // create our own markers from mapzen information i cant get the marker icon from mapzen to display
          const pointMarker = L.icon({
                                        iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Red-circle.svg/1024px-Red-circle.svg.png',
                                        iconSize: [15, 15]
                                    });

          const marker = L.marker([_lat, _lng],
            {
            icon: pointMarker,

            title: _lat + ' ' + _lng }
            )
            .bindTooltip(_selectedAddress , {permanent: true, direction: 'top', offset: [0, -5], })
            .addTo(this._map)
      });

**Comment by louh** [comment]
Hi @enocholumide,

I have created a very minimal test case at Leaflet's JS Bin here: https://playground-leaflet.rhcloud.com/vudab/1/edit?html,js,console,output

I have copied your options exactly (except for `position`) and your code for selecting a result. It appears to work as expected:

![screenshot 2017-04-04 11 59 17](https://cloud.githubusercontent.com/assets/2553268/24666480/79be1bea-192e-11e7-976f-da8164677ca6.png)

The request for the icon seems to have worked correctly as well:

![screenshot 2017-04-04 11 59 56](https://cloud.githubusercontent.com/assets/2553268/24666501/87088f38-192e-11e7-8ba5-ced95c2efce4.png)

I am not very familiar with Angular2, so obviously this test case doesn't cover everything. Can you try to add more to this test case until you can get your error to recur?

Thanks!

**Comment by chriszrc** [comment]
The problem here is that "marker-shadow.png" is ending up in the data:img declaration and it's not supposed to be there. I haven't tracked down why this is happening though :(

**Comment by chriszrc** [comment]
Ok, I found the problem. This has nothing to do with the mapzen geocoder (they simply create a default leaflet marker, and expect leaflet to be configured correctly). Angular 2/4 needs additional configuration to properly import the leaflet image assets. I'm using this plugin:

https://github.com/Asymmetrik/angular2-leaflet#angular-cli-marker-workaround

It describes the necessary steps, except it leaves out that since the image will end up in your "assets" folder (given the referenced configuration), you also need to update the imagePath to tell leaflet where to get it:

`L.Icon.Default.imagePath = "assets/";`

Now it works:

<img width="819" alt="screen shot 2017-08-03 at 11 20 02 am" src="https://user-images.githubusercontent.com/25695785/28929353-bb95a86c-783d-11e7-9a4e-0753ce36bf06.png">

**Comment by louh** [comment]
Thanks for your investigation, @chriszrc!
