### ISSUE TITLE
Filter out null island results

### ISSUE THREAD

**Issue by stevage** [pelias/leaflet-plugin#163]
For whatever reason, Mapzen's geocoder is returning a lot of results whose geometry is [0,0]. Showing these results as autocomplete suggestions is pretty poor UX, and undermines user confidence in the geocoder.

For instance, typing "bl" gives this:

<img width="212" alt="screen shot 2017-08-25 at 1 48 26 pm" src="https://user-images.githubusercontent.com/678344/29698893-27c0ccb4-899c-11e7-8d17-c50bfa8ec9bc.png">

Apart from the 3 results from Switzerland, the other 7 results are all null island.

**Comment by dianashk** [comment]
Hey @stevage, great catch! We missed a check for null island records in our openaddresses importer. Will add it shortly. Thanks for your feedback!

**Comment by dianashk** [comment]
This has been fixed! 🎉  🎉  Thanks again for reporting the issue. 

![screen shot 2017-09-15 at 12 37 52 pm](https://user-images.githubusercontent.com/5446511/30493624-d47b197e-9a12-11e7-90a9-d0efc2e9a6fc.png)

**Comment by stevage** [comment]
Awesome :) so it was fixed upstream, removing the need for a specific
filter here?

**Comment by dianashk** [comment]
@stevage, no we actually had a code change go through in a [linked PR](https://github.com/pelias/openaddresses/pull/277). No changes to the user interface of leaflet-geocoder or the API were made, however.
