### ISSUE TITLE
Demo link in readme should link to nextzen, not mapzen.

### ISSUE THREAD

**Issue by phist210** [pelias/leaflet-plugin#171]
README.md has a link to the demo page but links to the wrong domain.

Please change to:
https://nextzen.github.io/leaflet-geocoder

**Comment by nvkelso** [comment]
Fixed in https://github.com/nextzen/leaflet-geocoder/commit/d0f6bcb386fc1ac5c2a35bd313bdc28e8daaf755, but since Mapzen services are offline more changes will need to happen to make the demo work fully again.
