### ISSUE TITLE
Leaflet after search zoom doesnt load tiles

### ISSUE THREAD

**Issue by danielkp1234** [pelias/leaflet-plugin#180]
So when I zoom in a lot the mapbox tiles stop loading(don't think there are that closeup tiles for my area) so how would I make it so when I search it won't zoom
I'm using 
var geocoder = L.control.geocoder('search-MKZrG6M').addTo(map);
and the mapbox tiles are
mapbox://styles/mapbox/satellite-streets-v9

**Comment by missinglink** [comment]
Not tested, but try setting maxZoom:
https://leafletjs.com/examples/zoom-levels/

There is also an option in the `README` named `panToPoint`.
