### ISSUE TITLE
Sources parameter is not passed to the query

### ISSUE THREAD

**Issue by marc1091** [pelias/leaflet-plugin#181]
1. Sources  parameter is  ignored by the plugin -

var geocodingOptions = {
      url: 'http://localhost:4000/v1',
     layers: 'locality',
      expanded: true,
      sources: 'geonames',
    };
but the query does not  use  sources -

http://localhost:4000/v1/autocomplete?text=b&focus.point.lat=23.241346102386135&focus.point.lon=77.34375000000001&layers=locality

it defaults to whosonfirst

2. Abbreviations  work  fine  in browser   query

 http://localhost:4000/v1/autocomplete?text=b&focus.point.lat=23.241346102386135&focus.point.lon=77.34375000000001&layers=locality&sources=osm,oa,gn

but  the   plugin   requires   full text          -  
             sources: 'openaddresses, geonames',

**Comment by missinglink** [comment]
Hi @marc1091 the [documentation](https://github.com/pelias/leaflet-plugin#query-behavior) says that the option is called `params` and then you add query parameters in there.
Can you try again with a structure like this?

```javascript
var geocodingOptions = {
  ...
  params: {
    layers: 'locality',
    sources: 'osm,oa,gn'
  }
};
```
