### ISSUE TITLE
Compatibility w/ Mapzen Search or Self-Hosted Pelias

### ISSUE THREAD

**Issue by riordan** [pelias/leaflet-plugin#42]
Should be an easy config to allow a developer to change whether they're using our plain vanilla Mapzen Search, or running their own Pelias instance somewhere.

**Comment by louh** [comment]
There's a `url` option which defaults to `https://search.mapzen.com/v1` if not provided, but someone can set this to a different URL.

**Comment by riordan** [comment]
:thumbsup:

On 9/22/15 14:26, Lou Huang wrote:

> There's a |url| option which defaults to
> |https://search.mapzen.com/v1| if not provided, but someone can set
> this to a different URL.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pelias/leaflet-geocoder/issues/42#issuecomment-142372708.

## 

## 

David Riordan | Product Manager - Search | Mapzen
dave.riordan@mapzen.com | @riordan | gpg 235D 9DC9 5EF6 277C
https://mapzen.com | @mapzen
