### ISSUE TITLE
Desktop UX

### ISSUE THREAD

**Issue by souperneon** [pelias/leaflet-plugin#6]
### Closed state

[Customizable- can be defaulted to open or closed search box]

![pelias_leaflet_flow1 1](https://cloud.githubusercontent.com/assets/6125224/8234619/fe6d0402-15aa-11e5-9a6c-1a10a13c3674.png)
### Click state
1. Box slides open [customizable- opens right or left]
2. Search icon changes color
3. Placeholder/Helper text [customizable]

![pelias_leaflet_flow1 2](https://cloud.githubusercontent.com/assets/6125224/8234673/5fafeed2-15ab-11e5-8d6b-04d850c93461.png)
### User starts typing
1. Drop down appears with x auto-complete results 
2. 'x' (cancel) button appears as soon as the first letter is typed.
3. Embolden the letters in the results that are part of the user input
4. A 'pin' icon appears for points (poi's, addresses) and a 'globe' icon appears for polygons (cities, neighborhoods) [customizable icons]

![pelias_leaflet_flow1 3](https://cloud.githubusercontent.com/assets/6125224/8234776/00db4a04-15ac-11e5-9b17-47fffcffac3c.png)
### Browsing results
1. Browsing with mouse hover or arrow keys, as user views results one by one, fades the map to that result [customizable?]
2. Selected result gets a background color highlight and the icon also changes color [customizable- background color and icons]
3. Results that are points get a pin on the map with a tooltip (tooltip can be closed by clicking the 'x')
4. Results that are polygons just zoom that map to include the polygon in the viewport and no pin is dropped (nice to have- label for the polygon is highlighted)

![pelias_leaflet_flow1 4](https://cloud.githubusercontent.com/assets/6125224/8234903/e4c0eb8e-15ac-11e5-9a5a-30d3fa4a7a40.png)
### Panning the map/ Pressing enter or return on a result
1. Panning the map with a highlighted result, collapses the dropdown under the search box and populates the search box with the result highlighted/selected

![pelias_leaflet_flow1 5](https://cloud.githubusercontent.com/assets/6125224/8238589/c5a698da-15c4-11e5-8730-48197303969a.png)
### Clearing results
1. Clicking the 'x' in the search box, it clears the text in the box and the pins on the map (if any)
   ![pelias_leaflet_flow1 4a](https://cloud.githubusercontent.com/assets/6125224/8238519/58a088fe-15c4-11e5-954a-8d1a7672aa38.png)
2. (Future) Show recently search results in the dropdown when user first clicks in the search box or clears the search box
   ![pelias_leaflet_flow1 5a](https://cloud.githubusercontent.com/assets/6125224/8241193/e47b814c-15d5-11e5-9f63-2072cdd25e7d.png)

**Comment by hkrishna** [comment]
this looks good. will start working on it soon.

**Comment by dianashk** [comment]
Very cool. One small thing, we don't have polygon data in elasticsearch yet. So we have no way of knowing the size of a city or country to zoom out to. Maybe we just zoom out more than we would with points, but it wouldn't guarantee the whole region visible. Adding polygons is definitely something we have considered and are working towards, so this will eventually be working as the spec describes.

**Comment by souperneon** [comment]
That's fine… then let's just drop a pin on the map for now and as we have polygon data in, we can do the correct zoom etc.

**Comment by missinglink** [comment]
hey @souperneon this may be out-of-scope for the plugin but I saw this feature on http://adresse.data.gouv.fr/map/ that I like, if you search something like "Paris" (it's France only) then when you drag the map around it shows a little textbox at center,bottom which shows the nearest place to the map centroid.

**Comment by souperneon** [comment]
@missinglink interesting… haven't seen that before. 
Outside of this plugin, will it be useful for a Pelias demo?

**Comment by hkrishna** [comment]
Here's a first pass
http://rawgit.com/pelias/leaflet-geocoder/ux/index.html

**Comment by souperneon** [comment]
@hkrishna I played around with it a bit, are you still working on it?
I owe you some assets and I have some subtle refinements. Let me know and we can chat.

**Comment by souperneon** [comment]
I tested this on: http://pelias.github.io/leaflet-geocoder/. Here are some suggested improvements:
1. the 'x' overlaps with long text. Add a fade on the right of the text field or truncate
2. Customization: option to not drop a pin for a search result
3. Selecting a result (by clicking or pressing enter) from the drop down should populate that text in the search field and remove the blinking cursor from the search box
4. When user clicks 'x' to clear the search box, keep box open till user starts to pan the map or clicks outside the search box
5. Customization: persistent open search box
