### ISSUE TITLE
The demo application is really slow

### ISSUE THREAD

**Issue by hydrapolic** [pelias/leaflet-plugin#64]
Opening the demo on a 4 core 3.4GHz system with 16GB RAM and Firefox/Google chrome is a pain:
http://pelias.github.io/leaflet-geocoder/

The browser is stuck. Browser problem?

**Comment by riordan** [comment]
Web pages are a lot of work!

Really, your machine should have no problem with that. I'd be interested in seeing the CPU profile for the page. Try loading the page with [the cpu profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler) turned on and send us the results. We'll get our graphics team to take a look.

**Comment by hydrapolic** [comment]
Sorry it took me so long, here is the file (or where can I send it directly via email?)
https://www.sendspace.com/file/k6w85k

**Comment by louh** [comment]
Hi @hydrapolic, we'll send the profile over to the Tangram rendering team to see if they can make use of it.

In the meantime can you see if this demo page works as expected for you? https://mapzen.github.io/leaflet-geocoder/examples/

Thanks!

**Comment by hydrapolic** [comment]
Helllo @louh, yes that works fantastic :cocktail:

**Comment by louh** [comment]
Thanks for the response! I'll close this issue now, since Tangram rendering is separate from this plugin.
