### ISSUE TITLE
When bounds are provided, also obtain a lat-lng point to bias autocomplete results with

### ISSUE THREAD

**Issue by louh** [pelias/leaflet-plugin#65]

**Comment by missinglink** [comment]
hey @louh I'm just cleaning up this Milestone, could you provide more info on this issue, is it a big priority?

as I read it, it means:

> when the client sends the `focus.viewport.*` params it should _also_ send `focus.point.*` params.

If that is the case then it's a low priority as the backend API currently just computes the centroid [for you](https://github.com/pelias/api/blob/master/query/search.js#L70-L81)

**Comment by louh** [comment]
Hey @missinglink, I don't know how much autocomplete has changed in the last few weeks. Your reading is correct, but I'm writing it with the assumption that `/autocomplete` does not understand `boundary.rect.*`, and so the geocoder plugin itself should calculate the appropriate `focus.point.*` client-side. Is `focus.viewport.*` new? (or [undocumented](https://mapzen.com/documentation/search/autocomplete/#available-autocomplete-parameters)?)

**Comment by louh** [comment]
I found the answer to the `focus.viewport` question. https://github.com/pelias/api/pull/620 (SPOILER: it's gone)

**Comment by louh** [comment]
Closing this. The code to write this would be complicated & with too many edges (e.g. a `bounds` is provided but `focus` is set explicitly to false), and it would still not answer any questions about why autocomplete results (#131, #108) do not respect bounds. As questions come up we need to instruct developers to provide both `bounds` and `focus` options separately for `search` and `autocomplete` respectively.
