### ISSUE TITLE
Mobile UX

### ISSUE THREAD

**Issue by souperneon** [pelias/leaflet-plugin#7]
### Closed state

[Customizable- can be defaulted to open or closed search box]

![pelias_leaflet_flow-m1 1](https://cloud.githubusercontent.com/assets/6125224/8241393/182ed178-15d7-11e5-9b72-65571e02c7df.png)

![pelias_leaflet_flow-m1 1a](https://cloud.githubusercontent.com/assets/6125224/8241394/182eff2c-15d7-11e5-9ae6-c23fefa056a8.png)
### Tap state/ Active state
1. Keyboard slides up with cursor in the box
2. Search icon changes color
3. Placeholder/Helper text [customizable]
4. Deactivate and dim the map background

![pelias_leaflet_flow-m1 2](https://cloud.githubusercontent.com/assets/6125224/8241395/182f67dc-15d7-11e5-8c5f-a44726713150.png)

(Future) Show recently search results in the dropdown when user taps and activates search or clears the search box

![pelias_leaflet_flow-m1 2a](https://cloud.githubusercontent.com/assets/6125224/8241396/183073ac-15d7-11e5-8954-fa2b59155cf9.png)
### User starts typing
1. Drop down appears with x auto-complete results 
2. 'x' (cancel) button appears as soon as the first letter is typed.
3. Embolden the letters in the results that are part of the user input
4. A 'pin' icon appears for points (poi's, addresses) and a 'globe' icon appears for polygons (cities, neighborhoods) [customizable icons]

![pelias_leaflet_flow-m1 3](https://cloud.githubusercontent.com/assets/6125224/8241398/18313148-15d7-11e5-89af-51a2d1e5680a.png)

When user collapses keyboard, show the remaining results

![pelias_leaflet_flow-m1 3a](https://cloud.githubusercontent.com/assets/6125224/8241397/18310150-15d7-11e5-9186-657056b96eba.png)
### User selects a result
1. Result text populates the search box
2. Results that are points get a pin on the map with a tooltip (tooltip can be closed by clicking the 'x')
3. Results that are polygons just zoom that map to include the polygon in the viewport and no pin is dropped (nice to have- label for the polygon is highlighted)
4. Tapping 'x' in the search box clears the search box and the pin (if any) on the map

![pelias_leaflet_flow-m1 4](https://cloud.githubusercontent.com/assets/6125224/8241399/18360268-15d7-11e5-8841-033c45f1279c.png)

**Comment by souperneon** [comment]
I tested this on: http://pelias.github.io/leaflet-geocoder/. Here are some suggested improvements:
1. Search box should default to being persistent and open. Customization: ability to collapse to the button
2. Make the search field taller. At least 44px tall (is that possible?)
3.  Selecting a result (by tapping) from the drop down should populate that text in the search field, remove the blinking cursor from the search box and collapse the keyboard
4. the 'x' overlaps with long text. Add a fade on the right of the text field or truncate
5. Customization: option to not drop a pin for a search result
6. When user clicks 'x' to clear the search box, keep box active and keyboard up till user starts to pan the map or manually collapses the keyboard

**Comment by riordan** [comment]
:+1: Nice work.
