### ISSUE TITLE
Move this project to mapzen org

### ISSUE THREAD

**Issue by louh** [pelias/leaflet-plugin#80]

**Comment by riordan** [comment]
Goodbye old friend.

**Comment by orangejulius** [comment]
![goodbye](https://cloud.githubusercontent.com/assets/111716/11574848/0512b0d0-99dc-11e5-89d9-fc9d565f0640.gif)

**Comment by louh** [comment]
One of the big questions is this: do we also want to rename the package? It's currently at https://npmjs.com/package/pelias-leaflet-geocoder, but renaming it something like `mapzen-leaflet-geocoder` is going to break existing installs. Then again, it might be worth to rip this band-aid off right now instead of later...

**Comment by riordan** [comment]
Far better now than later.

**Comment by louh** [comment]
Opinions on naming?
- mapzen-leaflet-geocoder (closest to current)
- mapzen-search-leaflet (get the whole product name in there)
- mapzen-search-leaflet-geocoder (too long?)
- leaflet-mapzen-search (prefacing it with the environment it's plugging into, which is a pretty common pattern)

**Comment by louh** [comment]
Recapping a short discussion with @riordan today:

When we move the repository to the Mapzen organization, also rename the `npm` package to **`leaflet-geocoder-mapzen`** from `pelias-leaflet-geocoder`. "Leaflet" should come first so it's clear that it's a Leaflet plugin. "Geocoder" is next because that is specifically what it is and what it does. "Mapzen" is last to be clear that it is designed for the Mapzen service.

Further thoughts on the transition:
- The repository name will stay as-is.
- Named things in the code that refer to Pelias should remain as-is (we can revisit this in a major version bump).
- Consider renaming the JS and CSS files. This shouldn't matter for anyone installing via npm. Any manual downloads (or bower) means needing to adjust a file name reference.

I'm also very conflicted about whether this change requires a semantic version bump. It feels unnecessary to call this v2 even though moving/renaming things is technically a "breaking change", and this is the only breaking change. Since I plan to rename the package name anyway, this is actually a new entry in npm and bower, so conceptually you might think this is a "different package" even though I'd prefer to call it v1.3 just so this transition has a clear place in history without disrupting it too much.

In the meantime, we will leave the distribution files here on pelias/leaflet-geocoder, and leave a deprecation notice in the README and on npmjs.org pointing to the new repository and package locations. This should be enough to preserve functionality for anyone who is still depending on it in the near term.

Also: considering doing this first thing Monday so there's plenty of time to address issues.

Thoughts?!

**Comment by missinglink** [comment]
:+1:

**Comment by louh** [comment]
Done and released as https://github.com/mapzen/leaflet-geocoder/releases/tag/v1.3.0.

Placeholders are in place and existing links to the old repository should still work: https://www.npmjs.com/package/pelias-leaflet-geocoder

Anyone trying to `npm install pelias-leaflet-geocoder` will also see this message:
![screenshot 2015-12-07 15 36 14](https://cloud.githubusercontent.com/assets/2553268/11643133/df878638-9d0f-11e5-9e6e-9ef1e51189c9.png)
