### ISSUE TITLE
Overlapping of two geocoder

### ISSUE THREAD

**Issue by marcoamadori** [pelias/leaflet-plugin#81]
Hi!
I have added two different geocoders in the same map (I need them to create a travel planner, from point A - the first geocoder - to point B - the second geocoder).
They are one below the other.

The problem is that the list of results that appears below the first geocoder is hidden by the second geocoder. Is there a way to create a sort of order like layers?

**Comment by louh** [comment]
There's definitely an argument here for rewriting the DOM in the plugin to get around the positioning problems. For now, the easiest way to do this is get the first geocoder element to be at a higher z-index level than the second one.

``` js
document.querySelectorAll('.leaflet-pelias-control')[0].style.zIndex = 811;
```

**Comment by louh** [comment]
Hi @marcoamadori, I made an example page demonstrating this in action. https://mapzen.github.io/leaflet-geocoder/examples/two-geocoders.html

Hope that helps. Closing this now!
