### ISSUE TITLE
tangram style (demo)

### ISSUE THREAD

**Issue by missinglink** [pelias/leaflet-plugin#82]
how would you feel about changing the tangram style from 'refill' to 'scene' for the demo page?

I use the demo page at http://pelias.github.io/leaflet-geocoder to do user testing and people always comment on the tiles not being very cartographic ;)

**Comment by louh** [comment]
Is 'scene' the one here? http://tangrams.github.io/tangram/

**Comment by dianashk** [comment]
Let's ask Nathaniel and Geraldine which styles are ready for use and which would be most appropriate for this use case. The reason we chose this one is because it's one of the most popular styles out there and also has been designed specifically to highlight the data displayed over it, such as poi markers, rather than highlighting the cartographic features of the location. The markers tend to be less visible on _busier_ styles.

**Comment by riordan** [comment]
We've been advised to use one of the [three core styles](https://mapzen.com/blog/introducing-refill-cinnabar-and-zinc-styles-for-tangram):
- Refill (for lots of dots)
- Cinnabar (general purpose mapping, what most people are used to)
- Zinc (light/ ESRI gray, drawing things on a map)

We can also choose the level of precision for labeling (none, standard, lots).

It depends what we're showing off. Right now, it's plotting a single address. I'm kind of tempted to switch over to Cinnabar-lots of labels, which is the successor to the default `scene` for tangram. It'll look like more like the kind of map users would expect in navigation/placefinding contexts.

**Comment by louh** [comment]
So, one does not simply drop `scene.yaml` into Tangram.[[1](https://www.youtube.com/watch?v=r21CMDyPuGo)] There's a lot of JavaScript lurking in the background that makes the scene work, and it's all being controlled by dat GUI [floating quietly in the corner](http://tangrams.github.io/tangram/). I have, once, extracted a version of `scene.yaml` that can "do the right thing" without the GUI, but then that means having to maintain it separately from the Tangram demo, and I'm not volunteering. Also, that was also before Nathaniel and Geraldine were around, and I didn't have many other options. But with our choices now, `scene.yaml` just doesn't have good detail at the lower zoom levels and it isn't prioritized around massaging data presentation properly.

But don't take my word for it! Here, I dropped 'scene.yaml' into Tangram. [It doesn't work.](https://mapzen.github.io/leaflet-geocoder/examples/scene.html)

Through the magic of copy-paste, I've also made example pages of all three core styles (even Refill, for completeness' sake) so we can actually try to answer this question with empirical(?) evidence:
- [Cinnabar](https://mapzen.github.io/leaflet-geocoder/examples/cinnabar.html)
- [Zinc](https://mapzen.github.io/leaflet-geocoder/examples/zinc.html)
- [Refill](https://mapzen.github.io/leaflet-geocoder/examples/refill.html)

(n.b. do not link to or embed these pages; they are ethereal and will disappear sometime after this conversation has concluded.)

I'm personally a big fan of the Refill aesthetic, but ultimately I do agree that the best base map for user-testing is the one we ought to use.

**Comment by missinglink** [comment]
ok thanks for the feedback, sorry to be a pain, sounds like using 'scene' is not a good idea, so let's just leave it as-is?
