### ISSUE TITLE
[Browser Compatibility] Selecting a search result sets Search Box text to Undefined

### ISSUE THREAD

**Issue by riordan** [pelias/leaflet-plugin#9]
While using Firefox Desktop, searching for a place then selecting it changes the content of the search field to "undefined". It is supposed to put the name of the selected place into the search box.

![pelias-leaflet-firefox-undefined](https://cloud.githubusercontent.com/assets/227472/8621026/56da6b00-26f1-11e5-8a28-686acaa90788.gif)

To Reproduce:
- Use Firefox Desktop (untested in mobile at this point)
- Search for a place using typeahead search
- Explicitly select a result either by using keyboard navigation (which is a _nice_ add) or clicking the result with a mouse

Verified Does Not Occur in:
- iOS MobileSafari
- MacOS Safari
- Chrome Desktop MacOS

**Comment by hkrishna** [comment]
this is fixed https://github.com/pelias/leaflet-geocoder/commit/7d60d676b93c22749ffa859962587c1dd652ed46

**Comment by riordan** [comment]
👊

On Fri, Jul 10, 2015 at 11:54 AM, Harish Krishna notifications@github.com
wrote:

> this is fixed 7d60d67
> https://github.com/pelias/leaflet-geocoder/commit/7d60d676b93c22749ffa859962587c1dd652ed46
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pelias/leaflet-geocoder/issues/9#issuecomment-120442990
> .

## 

David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan https://twitter.com/riordan | gpg 235D9DC95EF6277C
https://keybase.io/riordan
Mapzen | https://mapzen.com | @mapzen https://twitter.com/search
