### ISSUE TITLE
Autocomplete results should filter by layer.

### ISSUE THREAD

**Issue by louh** [pelias/leaflet-plugin#93]
Currently, the `layers` option for the geocoder doesn't affect autocomplete queries:

> NOTE: layers is not available for the autocomplete query.

This provides a really strange experience because neither the application developer nor the end user expects results that are not in the layers that are set. However, the autocomplete endpoint does not do layer filtering because it slows down the cache.

Since `layers` is just sugar for the actual search parameter, and the autocomplete response also includes layers in the feature collection for results, what if we were to filter autocomplete responses on the client-side before rendering the results to UI (or sending to events, etc.)?

**Comment by louh** [comment]
To account for:
- No filtering is done if `layers` option is blank or null
- Expand to the correct list of layers for comparison if `layers` is set to `coarse`
  - Also do this in arrays if someone does, for instance, `['coarse', 'venue']`

**Comment by AndrewLWestover** [comment]
gs

**Comment by louh** [comment]
Done https://github.com/mapzen/leaflet-geocoder/pull/100, 238047ff06c0b0e89fed34d34c715ad2c2cbdb5a
