### ISSUE TITLE
How to get to and use the XY from the result of the Mapzen Leaflet Geocoder?

### ISSUE THREAD

**Issue by thundersnow-spatial** [pelias/leaflet-plugin#95]
I'm struggling is how to deal with with array of features that get created during the autocomplete process, and how to get the XY from the one result of the autocomplete the user selects.

I can see the XY coordinates in each object in the Array that is returned... but how to get to it...

From there, I'd like to feed that XY into a Geoserver service tying back to a PostGIS query...

Any thoughts? Thank you!

**Comment by louh** [comment]
Hi @mapbaker,

You can use the built in event listeners to listen for certain events that happen, such as when autocomplete results are received, and when the user selects a result. [Here's the documentation on events](https://github.com/mapzen/leaflet-geocoder#events) and a [demo](http://mapzen.github.io/leaflet-geocoder/examples/events.html) of events being fired. Each of these events will send relevant data to a callback function where you can do anything you want with it.

Did that help answer your question? 

Lou

**Comment by thundersnow-spatial** [comment]
Ah yes! I think that will do it! Many thanks for this!!!

**Comment by louh** [comment]
Great! Glad I could help.
