### ISSUE TITLE
Possible non-deterministic test

### ISSUE THREAD

**Issue by louh** [pelias/leaflet-plugin#99]
See this failure: https://circleci.com/gh/mapzen/leaflet-geocoder/194
And this fixed on rebuild: https://circleci.com/gh/mapzen/leaflet-geocoder/195

Managed to duplicate this problem locally.

The offending code is here: https://github.com/mapzen/leaflet-geocoder/blob/a42b6a8f2c33033cde399b40bebba250f8143f91/spec/suites/InterfaceSpec.js#L168-L182

The test fails because the expected map center is not quite at the given lat/lng point of the result. There is a slight margin of error.

Hypothesis: the center of the map is checked while in the middle of an incomplete animated pan. Usually the pan is completed by the time it's checked, so the test passes. Sometimes it is not.

Not sure if the right solution is to allow a certain amount of fuzziness to the test since most of the time it works. Maybe better to force the map to not animate when panning during a test.

**Comment by dianashk** [comment]
I think changing behavior during tests takes away from the validity of the test. Building some fuzziness into the test doesn't seem like a big deal, as long as it's a reasonable range. You could also consider adding timeouts of some arbitrary length to allow the map to stop animating.
